config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :carts, only: %i[index create update destroy]
  resources :categories, except: :show
  resources :items do
    member do
      delete :delete_image_attachment
    end
  end
  resources :restaurants
  devise_for :users, controllers: { sessions: 'custom_sessions' }
  resources :orders

  root 'welcome#index'
end

app/models/restaurant.rb
# frozen_string_literal: true

class Restaurant < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :users, through: :order_details, dependent: :destroy
  has_many :items, dependent: :destroy

  validates :name, length: { minimum: 2 }
  validates :description, length: { minimum: 2 }

  has_one_attached :avatar
end

app/controllers/restaurants_controller.rb
# frozen_string_literal: true

class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
    authorize @restaurants
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = 'Restaurant Created Successfully'
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = 'Restaurant Updated Successfully'
      redirect_to restaurants_path
    else
      render 'edit'
    end
  end

  def edit
    authorize @restaurant
  end

  def show
    @items = Item.where(restaurant_id: params[:id], status: 'publish')
    @categories = Category.all
    @cart = Cart.new
  end

  def destroy
    authorize @restaurant
    @restaurant.destroy
    respond_to do |format|
      format.js { render 'restaurant.js.erb' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_restaurant
    @restaurant = Restaurant.where_id(params[:id])
    content_not_found if @restaurant.blank?
  end

  # Only allow a list of trusted parameters through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :avatar)
  end
end

app/helpers/restaurants_helper.rb
# frozen_string_literal: true

module RestaurantsHelper
  def restaurant_avatar(restaurant)
    size = '50x50!'
    if restaurant.avatar.attached?
      image_tag restaurant.avatar.variant(resize: size).processed, class: 'rounded-circle'
    else
      image_tag 'default_hotel.png', class: 'rounded-circle'
    end
  end

  def restaurant_all_image(restaurant)
    if restaurant.avatar.attached?
      image_tag restaurant.avatar, width: '100%', height: '200px'
    else
      image_tag 'default_hotel.png', width: '100%', height: '200px'
    end
  end
end

app/views/restaurants/_form.html.erb
<div class="w-50 mx-auto mt-3">
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, class:"form-control" %>
  </div>


  <div class="actions text-center">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>
</div>

app/views/restaurants/edit.html.erb
<h1 class="text-center mt-5 pt-5">Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>
<div class="mx-auto">
<h5 class="text-left h6">Attached Image:</h5>

<%= restaurant_avatar(@restaurant) %> <br>
</div>
<%= link_to 'Show', @restaurant, class:"btn btn-info w-25" %> |
<%= link_to 'Back', restaurant_path, class:"btn btn-warning w-25" %>

app/views/restaurants/index.html.erb
<div class="pt-5 w-50 mx-auto">
<h1 class="mt-5">Restaurants</h1>
<%= link_to 'New Restaurants', new_restaurant_path,class: "btn btn-primary btn-sm w-25 float-right" %>
<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="2" class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.sort.reverse.each do |restaurant| %>
      <tr>
        <td><%= restaurant_avatar(restaurant) %></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.description %></td>
        <td class="text-center"><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td class="text-center"><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure you want to delete?' }, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

</div>

app/views/restaurants/new.html.erb
<h1 class="text-center mt-5 pt-5">New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>
<div class="mx-auto justify-center">
  <%= link_to 'Back', restaurants_path, class:"btn btn-warning ml-2 w-25" %>
</div>

app/views/restaurants/restaurant.js.erb
$('a[href="/restaurants/<%= @restaurant.id %>"]').parent().parent().remove()

app/views/restaurants/show.html.erb
<div class="container restaurant_show pt-5 mt-5">
  <div class="row">
  <h1>Filter By:</h1>
  <%= collection_select(:category, :id, @categories, :id, :name, {}, { :class=>"selectpicker w-100", "data-live-search" => "true"} ) %>
    <div class="col-sm-12 col-md-12 col-xs-12 no-padding">
      <div class="restaurant-table">
        <h1>
          <div class="row">
            <div class="col-sm-2 col-md-2 col-xs-2">
              <%= restaurant_avatar(@restaurant) %>
            </div>
            <div class="col-sm-10 col-md-10 col-xs-10 ">
              <%= @restaurant.name %>
            </div>
          </div>
        </h1>
          <div><%= render @items %>
        </div>
      </div>
    </div>
  </div>