config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :carts, only: %i[index create update destroy]
  resources :categories, except: :show
  resources :items do
    member do
      delete :delete_image_attachment
    end
  end
  resources :restaurants
  devise_for :users, controllers: { sessions: 'custom_sessions' }
  resources :orders

  root 'welcome#index'
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  has_many :category_items, dependent: :destroy
  has_many :categories, through: :category_items, dependent: :destroy

  has_many :order_items, dependent: :destroy
  has_many :carts, dependent: :destroy
  belongs_to :restaurant
  has_many_attached :item_image, dependent: :destroy

  validates :name, presence: true
  validates :status, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }

  paginates_per 15

  enum status: {
    publish: 0,
    unpublish: 1
  }

  before_validation :remove_empty_string

  private

  def remove_empty_string
    category_ids.compact
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_items, only: %i[show edit update destroy]
  before_action :gets_cat_res, only: %i[new edit]
  before_action :auth

  def index
    @items = authorize Item.page params[:page]
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = 'Items Created Successfully'
      redirect_to items_path
    else
      gets_cat_res
      render 'new'
    end
  end

  def new
    @item = authorize Item.new
  end

  def update
    if @item.update(item_params)
      flash[:notice] = 'Item Updated Successfully'
      redirect_to items_path
    else
      gets_cat_res
      render 'edit'
    end
  end

  def show
    @cart = Cart.new
  end

  def edit
    authorize @item
  end

  def destroy
    @item.destroy
    flash.now[:alert] = 'Item Deleted Successfully'
    respond_to do |format|
      format.js { render 'items.js.erb' }
    end
  end

  # to delete single image
  def delete_image_attachment
    @item_image = ActiveStorage::Attachment.find(params[:id]).purge
    redirect_back(fallback_location: request.referer)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_items
    @item = Item.where_id(params[:id])
    content_not_found if @item.blank?
  end

  def gets_cat_res
    @categories = Category.plucked
    @restaurant = Restaurant.plucked
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:name, :description, :restaurant_id, :price, :status, item_image: [], category_ids: [])
  end

  def auth
    authorize Item
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
  def item_avatar(item)
    size = '100%x100%!'
    if item.item_image[0]
      image_tag item.item_image[0].variant(resize: size).processed
    else
      image_tag 'default_item.png', class: 'w-100'
    end
  end
end

app/views/items/_allItem.html.erb
<% if @items %>
  <% @items.sort.reverse.each do |item| %>
    <tr>
      <td class="image-frame"><%= item_avatar(item) %></td>
      <td><%= item.name %></td>
      <td><%= item.description %></td>
      <td><%= item.price %></td>
      <td><%= item.status %></td>
      <td><%= item.restaurant.name %></td>
      <td class="text-center"><%= link_to 'Show', item_path(item) %></td>
      <td class="text-center"><%= link_to 'Edit', edit_item_path(item) %></td>
      <td class="text-center"><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure you want to delete?' }, remote: true %></td>
    </tr>
  <% end %>
<% end %>

app/views/items/_form.html.erb
<div class="w-50 mx-auto mt-3">
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :restaurant %>
    <%= form.select :restaurant_id, options_for_select(@restaurant), {}, {:class=>"selectpicker w-100", "data-live-search" => "true"} if @restaurant %>
  </div>

  <div class="form-group">
    <%= form.label :category_ids, "Select Category" %>
    <%= form.select :category_ids, options_for_select(@categories, item.categories.ids), {include_blank: false, include_hidden: false}, {:multiple => true, :class=>"selectpicker w-100", "data-live-search" => "true"} if @categories %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :item_image %>
     <%= form.file_field :item_image, multiple: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :status, 'Product Status'%><br />
    <%= form.radio_button :status, 'publish', :checked => true %> Show <br>
     <%= form.radio_button :status, 'unpublish' %> Hide <br>
  </div>

  <div class="actions text-center">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>
</div>

app/views/items/_item.html.erb
<ul class="text-left items_by_cat">
  <li class="<% item.categories.each do |item| %>
      <%= item.id %>
    <% end %>"
  >

    <label class="circle-img d-flex float-left mr-2"><%= item_avatar(item) %></label>
    <label><%= item.name %></label>
    <label class="desc"><%= item.description if item.description %></label>
    <label>Rs. <%= item.price %></label>
    <% item.categories.sort.reverse.each do |item| %>
      <span class="badge badge-success my-2"><%= item.name %></span>
    <% end %>
    <%= form_for(@cart, remote: true) do |f| %>
      <%= f.hidden_field :item_id, value: item.id %>
      <%= f.hidden_field :price, value: item.price %>
      <%= f.hidden_field :restaurant_id, value: item.restaurant_id %>
      <div class="form-group">
        <%= f.hidden_field :quantity, value: 1 %>
      </div>
      <%= f.submit "Add to cart", class: 'btn btn-primary btn-sm w-25' %>
    <% end %>
  </li>
</ul>

app/views/items/create.html.erb
<h1 class="text-center mt-5 pt-5">Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item, class:"btn btn-info w-25" %> |
<%= link_to 'Back', item_path, class:"btn btn-warning w-25" %>

app/views/items/edit.html.erb
<h1 class="text-center mt-3">Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item, class:"btn btn-info" %> |
<%= link_to 'Back', item_path, class:"btn btn-warning" %>

app/views/items/index.html.erb
<div class="pt-5 w-50 mx-auto ">
<h1 class="mt-5">Items</h1>
<%= link_to 'New Item', new_item_path,class: "btn btn-primary btn-sm w-25 float-right" %>
<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Status</th>
      <th>Restaurant</th>
      <th colspan="3" class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody class="allitems">
    <%= render 'allItem' %>
  </tbody>
</table>
<br>

</div>
<div class="pags d-flex justify-content-center">
  <%= paginate @items %>
</div>

app/views/items/items.js.erb
$('a[href="/items/<%= @item.id %>"]').parent().parent().remove()

app/views/items/new.html.erb
<h1 class="text-center mt-5 pt-5">New Restaurant</h1>

<%= render 'form', item: @item %>
<div class="mx-auto justify-center">
  <%= link_to 'Back', items_path, class:"btn btn-warning ml-2 w-25" %>
</div>

app/views/items/show.html.erb
<div class="mx-auto my-5 py-5 w-100">
  <div class="card mx-auto" style="width: 18rem;">
    <%= item_avatar(@item) %>
    <div class="card-body">
      <h5 class="card-title"><%= @item.name %></h5>
      <p class="card-text"><%= @item.description %></p>
      <p><%= @item.price %></p>
      <% if current_user.user? %>
        <%= form_for(@cart, remote: true) do |f| %>
          <%= f.hidden_field :item_id, value: @item.id %>
          <%= f.hidden_field :price, value: @item.price %>
          <%= f.hidden_field :restaurant_id, value: @item.restaurant_id %>
          <div class="form-group">
            <%= f.hidden_field :quantity, value: 1 %>
          </div>
          <%= f.submit "Add to cart", class: 'btn btn-primary btn-sm w-50' %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="mx-auto w-100 text-center mt-5">
    <h3>All Images</h3>
    <div class="container-fluid mt-5">
      <div class="row">
        <% @item.item_image.sort.reverse.each do |image| %>
          <div class="col-md-4 text-center">
            <div class="mw-75">
              <% if @item.item_image.count > 1 && current_user.admin? %>
                <%= link_to 'x', delete_image_attachment_item_url(image.id), method: :delete,
                        data: { confirm: 'Are you sure?' }, class:"close delete_img" %>
              <% end %>
              <%= image_tag image, class:"w-100 mt-2" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>