config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :carts, only: %i[index create update destroy]
  resources :categories, except: :show
  resources :items do
    member do
      delete :delete_image_attachment
    end
  end
  resources :restaurants
  devise_for :users, controllers: { sessions: 'custom_sessions' }
  resources :orders

  root 'welcome#index'
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :category_items, dependent: :destroy
  has_many :items, through: :category_items, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2 }
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update destroy]
  before_action :auth
  def index
    @categories = Category.all
    authorize @categories
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category Created Successfully'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def new
    @category = Category.new
  end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category Updated Successfully'
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def edit; end

  def destroy
    @category.destroy
    flash.now[:notice] = 'Category Deleted Successfully'
    respond_to do |format|
      format.js { render 'category.js.erb' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.where_id(params[:id])
    content_not_found if @category.blank?
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name)
  end

  def auth
    authorize Category
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="w-50 mx-auto mt-3">
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>


  <div class="actions text-center">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>
</div>

app/views/categories/category.js.erb
$('a[href="/categories/<%= @category.id %>"]').parent().parent().remove()

app/views/categories/edit.html.erb
<h1 class="text-center mt-3">Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category, class:"btn btn-info" %> |
<%= link_to 'Back', category_path, class:"btn btn-warning" %>

app/views/categories/index.html.erb
<div class="pt-5 w-50 mx-auto">
<h1 class="mt-5">Categories</h1>
<%= link_to 'New Category', new_category_path,class: "btn btn-primary btn-sm w-25 float-right" %>
<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th colspan="2" class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.sort.reverse.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td class="text-center"><%= link_to 'Edit', edit_category_path(category) %></td>
        <td class="text-center"><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure you want to delete?' }, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-5 pt-5">New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path, class:"btn btn-warning ml-2" %>