config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :carts, only: %i[index create update destroy]
  resources :categories, except: :show
  resources :items do
    member do
      delete :delete_image_attachment
    end
  end
  resources :restaurants
  devise_for :users, controllers: { sessions: 'custom_sessions' }
  resources :orders

  root 'welcome#index'
end

app/views/layouts/_footer.html.erb
<footer class="-bg-footer" id="footer">
  <div class="container-fluid">
    <div class="row footer-align">
      <div class="col-md-4 col-sm-4">
        <h5>Lahore</h5>
        <hr class="hr-foot">
        <div class="footer-items">
          <p class="footer">
            The EU-27 has an estimated 1.6m businesses involved in 'accommodation and food services', more than 75% of which are small and medium enterprises.
          </p>
          <ul class="social-networks">
            <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
            <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
          </ul>
        </div>
      </div>
      <div class="col-md-4 col-sm-4">
        <h5>Our contact</h5>
        <hr class="hr-foot">
        <div class="footer-items">
          <address>
            15-B DHA Phase 5
            <br>
            Lahore, Punjab
            <br>
            Pakistan
            <br>
            <i class="fa fa-phone address"></i> +92 300 000 0000
            <br>
            <i class="fa fa-fax address"></i> +92 300 000 0000
            <br>
            <i class="fa fa-envelope address"></i> <a href="mailto:dinnerdash@gmail.com">dinnerdash@gmail.com</a>
          </address>
        </div>
      </div>
      <div class="col-md-4 col-sm-4">
        <h5>Open hours</h5>
        <hr class="hr-foot">
        <div class="footer-items">
          <ul>
            <li>Mon-Fri: 08:00-22:00</li>
            <li>Sat    : 09:00-22:00</li>
            <li>Sun    : 09:00-16:00</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <a class="to-top" href="#myPage" title="toTop">
    <i class="fa fa-chevron-up"></i>
  </a>
</footer>
<div class="footer-copyright">
  <p>&copy <%= Time.zone.now.year %> Copyright by  <a href="#"> Dinner Dash</a></p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md bg-nav navbar-dark fixed-top">
  <%= link_to 'Dinner Dash', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="#about">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#restaurant">Restaurants</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#contact">Contact</a>
      </li>

      <li class="nav-item">
        <%= link_to 'Cart', carts_path, class: "nav-link bold text-white" %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, class:"nav-link", method: :delete, data: { confirm: 'Are you sure you want to Logout?' } %>
        </li>
        <li class="nav-item">
        <a class="nav-link" id="menu-toggle"><i class="fa fa-bars" aria-hidden="true"></i></a>
      </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Signup', new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_notification.html.erb
<div class="noti">
  <% unless notice.nil? %>
    <p class="alert alert-warning w-100 mt-5 pt-4"><%= notice %></p>
  <% end %>
  <% unless alert.nil? %>
    <p class="alert alert-danger w-100 mt-5 pt-4"><%= alert %></p>
  <% end %>
</div>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
  <ul class="sidebar-nav mt-5 pt-3">
    <li class="sidebar-brand">
      <%= link_to 'Dinner Dash v2', root_path %>
    </li>
    <% if user_signed_in? == true   %>
      <li>
        <%= link_to 'Previous Orders', orders_path %>
      </li>
      <% if current_user.admin? %>
        <li>
          <%= link_to 'Items', items_path %>
        </li>
        <li>
          <%= link_to 'Restaurants',restaurants_path %>
        </li>
        <li>
          <%= link_to 'Categories', categories_path %>
        </li>
      <% end %>
      <li>
        <%= link_to 'Logout', destroy_user_session_path, class:"nav-link", method: :delete, data: { confirm: 'Are you sure you want to Logout?' } %>
      </li>
    <% end %>
  </ul>
</div>
<!-- /#sidebar-wrapper -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dinner Dash</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="wrapper">
      <%= render "layouts/sidebar" %>
      <div id="page-content-wrapper">
        <%= render "layouts/navbar" %>
        <div class="content">
        <%= render 'layouts/notification' %>
        <%= yield %>
        </div>
        <%= render "layouts/footer" %>
      </div>
    </div>
  </body>
</html>